AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This lab is an environment for creating an Amazon VPC and Amazon EC2 instance 
  (and other supporting elements) using an AWS CloudFormation template. 
  The goal of this lab is to create a CloudFormation template with specified components.

Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'

  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId:
        Ref: MyVPC
      InternetGatewayId:
        Ref: InternetGateway

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH access from anywhere
      VpcId:
        Ref: MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MySubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: MyVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false

  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-01cd4de4363ab6ee8  # Amazon linux 2023
      SubnetId:
        Ref: MySubnet
      SecurityGroupIds:
        - Ref: MySecurityGroup

Outputs:
  VPCId:
    Description: The ID of the VPC
    Value:
      Ref: MyVPC
  SubnetId:
    Description: The ID of the Subnet
    Value:
      Ref: MySubnet
  InstanceId:
    Description: The ID of the EC2 Instance
    Value:
      Ref: MyEC2Instance
